# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storage: 
  storageClassName: manual
  storageCapacity: 10Gi
  accessMode: ReadWriteMany

env:        
  - name: POSTGRES_USER
    value: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    value: POSTGRES_PASSWORD
  - name: POSTGRES_DB
    value: POSTGRES_DB

replicaCount: 1

image:
  repository: "bitnami/postgresql"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "postgres"
fullnameOverride: "postgres"


podAnnotations: {}
podLabels: {
  app: postgres
}

service:
  type: ClusterIP
  port: 5432


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true