apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  config.json: |
    {
      "host": "0.0.0.0",
      "port": "8000",
      "dsn": "host=10.105.167.213 port=5432 user=postgres password=postgres dbname=users sslmode=disable"
    }